### ISSUE TITLE
If there is a user authorization is better.

### ISSUE THREAD

**Issue by xiwc** [chejen/keys-translations-manager#4]

**Comment by chejen** [comment]
Hi @xiwc, thanks for your advice! Initially, the project is designed to support team member development. We hope every team member can contribute to translate arbitrarily, that's why we didn't put authorization into it. Since authorization might be useful when collaborating with the other team, we're considering adding it in the future (might not be soon, though.)

**Comment by xiwc** [comment]
@chejen  3ks for your answers.
